version: "3.3"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  go-traefik:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.go-traefik.rule=Host(`localhost`)"
      - "traefik.http.routers.go-traefik.entrypoints=web"
    ports:
      - "5577:5577"

  mongodb:
    container_name: mongodb
    image: mongo:4.4
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    command: mongod

volumes:
  mongodb: {}
